/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scenePPT.gltf 
*/

import felt from '../img/Felt.jpg'
import React, { useEffect, useRef } from 'react'
import { useGLTF, PerspectiveCamera, useAnimations, useTexture } from '@react-three/drei'
import TextureFurniture from '../components/Textures/furnituresTextures/TextureFurniture'
import TextureChairLegs from '../components/Textures/chairsTextures/TextureChairLegs'
import TableTexture from '../components/Textures/table/TableTexture'
import TextureFloor from './Textures/floorTexture/TextureFloor'
import TextureRoom from './Textures/roomTexture/TextureRoom'

export function Scene({ playAnimation, props }) {
    const group = useRef()
    const feltTable = new useTexture(felt)
    const { nodes, materials, animations } = useGLTF('../public/models/scenePPT.gltf')
    const { actions } = useAnimations(animations, group)
    useEffect(() => {
        if (playAnimation) {
            actions["CameraAction"].play().setLoop(1, 0);
            actions["CameraAction"].clampWhenFinished = true;
        }
    }, [playAnimation]);
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <PerspectiveCamera name="Camera" makeDefault={true} far={100} near={0.1} fov={22.895} position={[0.325, 14.219, 18.074]} scale={2.065} />
                <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials.MADERA1} position={[0.474, 5.906, 8.827]} rotation={[0, -Math.PI / 2, 0]} scale={[-3.814, -0.366, -4.498]} >
                    <TableTexture />
                </mesh>
                <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials.alfombra} position={[0.474, 5.906, 8.827]} rotation={[0, -Math.PI / 2, 0]} scale={[-3.814, -0.366, -4.498]} >
                    <meshStandardMaterial map={feltTable} color={'#139bef'} />
                </mesh>
                <group name="tv" position={[0.314, 14.447, -11.559]} rotation={[Math.PI / 2, 0, 0]} scale={[9.349, 0.584, 5.259]}>
                    <mesh name="Plane004" geometry={nodes.Plane004.geometry} material={materials.tv} />
                    <mesh name="Plane004_1" geometry={nodes.Plane004_1.geometry} material={materials['tv screen.001']} />
                    <mesh name="Plane004_2" geometry={nodes.Plane004_2.geometry} material={materials['back tv']} />
                </group>
                <mesh name="table" geometry={nodes.table.geometry} material={materials.MADERA1} position={[0.274, 1.067, -8.616]} scale={[10.677, 4.57, 2.344]}>
                    <mesh name="Plane011" geometry={nodes.Plane011.geometry} material={materials.MADERA1} position={[0, 0.035, 0]} scale={[0.034, 0.1, 0.195]} >
                        <TextureFurniture />
                    </mesh>
                    <TextureFurniture />
                </mesh>
                <group name="Plane001" position={[-18.824, 16.036, 5.922]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[4.366, 3.964, 3.964]}>
                    <mesh name="Plane013" geometry={nodes.Plane013.geometry} material={materials['MADERA1.001']} >
                        <TextureFurniture />
                    </mesh>
                    <mesh name="Plane013_1" geometry={nodes.Plane013_1.geometry} material={materials['Material.005']} />
                    <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.006']} position={[-0.001, -0.004, 0.001]} scale={[0.927, 0.683, 0.704]} />
                </group>
                <mesh name="Box001" geometry={nodes.Box001.geometry} material={materials['17 - Default.001']} position={[-6.095, 4.428, 7.877]} rotation={[0, 1.502, 0]} scale={0.085} >
                    <meshStandardMaterial color={'#176085'} />
                </mesh>
                <mesh name="Line009" geometry={nodes.Line009.geometry} material={materials.MADERA1} position={[-5.527, 2.328, 7.954]} rotation={[0, 1.502, 0]} scale={0.085} >
                    <TextureChairLegs />
                </mesh>
                <mesh name="Line010" geometry={nodes.Line010.geometry} material={materials.MADERA1} position={[-7.142, 2.328, 7.875]} rotation={[0, 1.502, 0]} scale={0.085} >
                    <TextureChairLegs />
                </mesh>
                <mesh name="Plane009" geometry={nodes.Plane009.geometry} material={materials['17 - Default.001']} position={[-7.145, 5.564, 7.839]} rotation={[0, 1.502, 0]} scale={0.085}
                >
                    <meshStandardMaterial color={'#176085'} />
                </mesh>
                <mesh name="Plane009001" geometry={nodes.Plane009001.geometry} material={materials['17 - Default.001']} position={[7.992, 5.564, 7.88]} rotation={[0, -1.559, 0]} scale={0.085} >
                    <meshStandardMaterial color={'#176085'} />
                </mesh>
                <mesh name="Line010001" geometry={nodes.Line010001.geometry} material={materials.MADERA1} position={[7.987, 2.328, 7.844]} rotation={[0, -1.559, 0]} scale={0.085} >
                    <TextureChairLegs />
                </mesh>
                <mesh name="Line009001" geometry={nodes.Line009001.geometry} material={materials.MADERA1} position={[6.369, 2.328, 7.894]} rotation={[0, -1.559, 0]} scale={0.085} >
                    <TextureChairLegs />
                </mesh>
                <mesh name="Box001001" geometry={nodes.Box001001.geometry} material={materials['17 - Default.001']} position={[6.943, 4.428, 7.926]} rotation={[0, -1.559, 0]} scale={0.085} >
                    <meshStandardMaterial color={'#176085'} />
                </mesh>
                <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials['17 - Default']} position={[0.818, 14.629, 0]} scale={[23.468, 14.213, 15.203]} >
                    <TextureRoom></TextureRoom>
                </mesh>
                <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials['17 - Default']} position={[0.818, 14.629, 0]} scale={[23.468, 14.213, 15.203]}>
                    <TextureFloor />
                </mesh>
            </group>
        </group>
    )
}

useGLTF.preload('../public/models/scenePPT.gltf')
